language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: pages
  repo: collabhq/collabhq.github.io
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build
  on:
    branch: site
notifications:
  slack:
    secure: JH3K2D85rZjQFZQFJi2nZxknmOMiEEUnjVfk0YhzRwX4O/0gOr1zIV6ufL3VPfFPP7yoe7xxTH2CkkBKLeQE/gyJm5L5KEkz6BXKq/Xsv5nrIjsIsYE4khS5jQ8STlfuora5CXy0jo5tbxjfWLmmY3VdH9Hc4bhJHuSfkrHCrg38k+MX1RfWbWoAtBTLc64ez7MTa/NkR+/nhPU8V/7p4adUCUOfff6ZeLruTu7RPCfspf2d0vfaeQ2x+QlQZ/63dM1AjNS4K46mF2gXfSlhO/moahguJjMIFtdQPCvQ/gYehDyI3BuegwJSB1TyXl3mj4Z+szozTf8E8MNZgHWMy1j4Im4gofn5FAACWgNtsKbZzUiv5rOkoXbCWG3mTab9t+uJt6uwHENJyifwcRQ3zJ4pzOkfwH/E5RGb5BycBLYIJxFhqCky7XB6wjKQULXVVBr5UNx71pns5VfQLmv2HyKsWHEPUmjtMIYKZMFIAxOV90CpEgS0y94PxhqxazDaoc5uv7qCiz+qWkpGXf6dMpEQJx2GbAHWfqQJpQLbJkrQbNM+WOsFyWR3leYUe+rYT1NP0l5/OrmW1k5m70YupI3ersklgdISUCNmTJDQsNFUbodYkxYwVHyq1clrmFZekpjEPTdiNowYo4bGsnIaUNPSyfI3kH/z3igg6IlHXU0=
